server:
  port: 8888
spring:
  application:
    name: configuration-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pawel0802/spring-cloud-demo-1
          search-paths: configuration-files
          order: 1
        encrypt:
          enabled: false